#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

bs_enabled() {
	local dev
	for dev in $(uci -q show wireless | grep 'bandsteering=.1.' | cut -d. -f2); do
		return 0
	done
	return 1
}

start_service() {
	bs_enabled || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/bndstrg
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "wireless"
}

reload_service() {
	stop
	start
}
