#!/bin/sh

dev=br-lan
hqos_path=/sys/kernel/debug/hnat

stop_qos() {
	tc qdisc del dev $dev root 2>/dev/null
	tc qdisc del dev $dev ingress 2>/dev/null
	tc qdisc del dev ${dev}-ifb root 2>/dev/null
	ip link del dev ${dev}-ifb 2>/dev/null
}

start_qos() {
	local dl=$1
	local up=$2

	tc qdisc add dev $dev root handle 1: htb
	tc class add dev $dev parent 1: classid 1:1 htb rate ${dl}mbit

	ip link add dev ${dev}-ifb name ${dev}-ifb type ifb
	ip link set dev ${dev}-ifb up

	tc qdisc add dev ${dev}-ifb root handle 1: htb
	tc class add dev ${dev}-ifb parent 1: classid 1:1 htb rate ${up}mbit

	tc qdisc add dev $dev ingress
	tc filter add dev $dev parent ffff: protocol ip u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev ${dev}-ifb
}

nft_stop() {
	nft delete table inet eqos 2>/dev/null
	echo 0 > $hqos_path/qos_toggle 2>/dev/null
	echo "10 0" > $hqos_path/hnat_setting 2>/dev/null
	echo "11 30" > $hqos_path/hnat_setting 2>/dev/null
	for i in $(seq 0 7); do
		[ -f $hqos_path/qdma_txq$i ] && echo 0 0 0 0 0 4 4 > $hqos_path/qdma_txq$i
	done
	for i in $(seq 8 15); do
		[ -f $hqos_path/qdma_txq$i ] && echo 1 0 0 0 0 4 4 > $hqos_path/qdma_txq$i
	done
	echo 1 wrr 1000000 > $hqos_path/qdma_sch0 2>/dev/null
	echo 1 wrr 1000000 > $hqos_path/qdma_sch1 2>/dev/null
	echo 1 wrr 1000000 > $hqos_path/qdma_sch2 2>/dev/null
	echo 1 wrr 1000000 > $hqos_path/qdma_sch3 2>/dev/null
	sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user 2>/dev/null
}

nft_start_prepare() {
	nft add table inet eqos 2>/dev/null
	nft flush table inet eqos 2>/dev/null
	nft add chain inet eqos forward '{ type filter hook forward priority mangle; policy accept; }' 2>/dev/null
	# Reset DSCP on all forwarded traffic through br-lan
	nft add rule inet eqos forward iifname "br-lan" ip dscp set cs0
	nft add rule inet eqos forward oifname "br-lan" ip dscp set cs0
	nft add rule inet eqos forward iifname "br-lan" ip6 dscp set cs0
	nft add rule inet eqos forward oifname "br-lan" ip6 dscp set cs0
}

nft_start_initial() {
	echo 1 > $hqos_path/qos_toggle 2>/dev/null
	echo 1 wrr 1000000 > $hqos_path/qdma_sch0 2>/dev/null
	echo 1 wrr 1000000 > $hqos_path/qdma_sch1 2>/dev/null
	echo 0 0 0 0 0 0 0 > $hqos_path/qdma_txq0 2>/dev/null
	echo 1 0 0 0 0 0 0 > $hqos_path/qdma_txq8 2>/dev/null
	echo "11 5" > $hqos_path/hnat_setting 2>/dev/null
	uci -q set "turboacc.config.fastpath_mh_eth_hnat_bind_rate=5"
	uci -q commit "turboacc"
	sed -i '/\/etc\/init.d\/eqos start/d' /etc/firewall.user 2>/dev/null
	echo "/etc/init.d/eqos start" >> /etc/firewall.user
	echo "10 1" > $hqos_path/hnat_setting 2>/dev/null
}


case "$1" in
	"stop")
		stop_qos
		nft_stop
	;;
	"start")
		stop_qos
		nft_start_prepare
		start_qos $2 $3
		nft_start_initial
		echo 1 wrr $(($3*1000)) > $hqos_path/qdma_sch2 2>/dev/null
		echo 1 wrr $(($2*1000)) > $hqos_path/qdma_sch3 2>/dev/null
	;;
	"add")
		ip="$2"
		dl="$3"
		up="$4"
		id="$5"
		macaddr="$6"
		cnt=$(tc class show dev $dev | wc -l)
		# Detect number of QDMA queues and calculate pair offset
		max_txq=$(ls -d $hqos_path/qdma_txq* 2>/dev/null | wc -l)
		half_txq=$((max_txq / 2))
		idpair=$((id + half_txq))

		if [ $id -lt $half_txq ]; then
			if [ $up -ne 0 ]; then
				[ -f $hqos_path/qdma_txq${id} ] && echo 2 0 0 1 ${up} 4 1 > $hqos_path/qdma_txq${id}
				nft add rule inet eqos forward ip saddr $ip ip dscp set $id meta mark set $id
			fi
			if [ $dl -ne 0 ]; then
				[ -f $hqos_path/qdma_txq${idpair} ] && echo 3 0 0 1 ${dl} 4 1 > $hqos_path/qdma_txq${idpair}
				nft add rule inet eqos forward ip daddr $ip ip dscp set $idpair meta mark set $idpair
			fi
		else
			if [ $up -ne 0 ]; then
				nft add rule inet eqos forward ip saddr $ip meta mark set 0x99
			fi
			if [ $dl -ne 0 ]; then
				nft add rule inet eqos forward ip daddr $ip meta mark set 0x99
			fi
		fi
		if [ $id -ge $half_txq ]; then
			tc class add dev $dev parent 1:1 classid 1:1$cnt htb rate ${dl}kbit ceil ${dl}kbit
			tc filter add dev $dev parent 1:0 protocol ip u32 match ip dst $ip flowid 1:1$cnt

			tc class add dev ${dev}-ifb parent 1:1 classid 1:1$cnt htb rate ${up}kbit ceil ${up}kbit
			tc filter add dev ${dev}-ifb parent 1:0 protocol ip u32 match ip src $ip flowid 1:1$cnt
		fi
	;;
	*)
		echo "Usage: $0 <command> [options]"
		echo "Commands:"
		echo "  start dl_rate up_rate       #Total bandwidth (Mbit/s)"
		echo "  stop"
		echo "  add ip dl_rate up_rate      #Limiting the bandwidth of a single IP (kbit/s)"
		echo "Example:"
		echo "  $0 start 30 20              # Total bandwidth: down 30Mbit/s up 20Mbit/s"
		echo "  $0 add 192.168.22.12 10 2   # down 10kbit/s  up 2kbit/s"
	;;
esac
