#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    local sta_found=$(uci show wireless | grep -E "\.mode='sta'$" || echo "")
    
    if [ -z "$sta_found" ]; then
        return 0
    fi
    
	procd_open_instance
	procd_set_param command /usr/sbin/mtkreconnect
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "wireless"
}

reload_service() {
	stop
	start
}
